# This file is generated by composer-plugin-nixify.
# Manual changes might be lost - proceed with caution!

{ lib, php, phpPackages, unzip, stdenv, runCommandLocal, writeText, fetchurl

# Default fetcher.
, fetcher ? (args: fetchurl { inherit (args) name urls sha256; })

}: src:

with lib;

let
  data = builtins.fromJSON ''
    {
    "cacheEntries": [
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "dflydev_dot-access-data-3.0.2.0",
            "urls": [
                "https://api.github.com/repos/dflydev/dflydev-dot-access-data/zipball/f41715465d65213d644d3141a6a93081be5d3549"
            ],
            "cacheFile": "dflydev/dot-access-data/5872417a18bbb69b106dc09a3b09c46b193e0110.zip",
            "sha256": "b2ae92836d920d2a968b32acd80e1c39a1446c749ddae28dc806408c7096ebed"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "doctrine_annotations-1.13.3.0",
            "urls": [
                "https://api.github.com/repos/doctrine/annotations/zipball/648b0343343565c4a056bfc8392201385e8d89f0"
            ],
            "cacheFile": "doctrine/annotations/6185e4843a8f5c9d48f8518572b216612da202a5.zip",
            "sha256": "a74c0120363de1eea6d324b92324e3b99e81e179553f269fb0ca5cac7cc07d56"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "doctrine_cache-2.2.0.0",
            "urls": [
                "https://api.github.com/repos/doctrine/cache/zipball/1ca8f21980e770095a31456042471a57bc4c68fb"
            ],
            "cacheFile": "doctrine/cache/3d10cdf80c6a538fe80c85b81ed43c4c89c2e472.zip",
            "sha256": "5a8799a67c97aab8a40b91eaa5a7af2db2e7c2b301a34ef60ae7e33a5e5211dd"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "doctrine_collections-1.8.0.0",
            "urls": [
                "https://api.github.com/repos/doctrine/collections/zipball/2b44dd4cbca8b5744327de78bafef5945c7e7b5e"
            ],
            "cacheFile": "doctrine/collections/2941fa6c1027968e7cdcb511da8612248a7ec8eb.zip",
            "sha256": "c81ade20559401923714f00851a7074c5fad2dfdab93571b31fbce93bb140532"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "doctrine_common-3.4.3.0",
            "urls": [
                "https://api.github.com/repos/doctrine/common/zipball/8b5e5650391f851ed58910b3e3d48a71062eeced"
            ],
            "cacheFile": "doctrine/common/b5038a8d0612b9cfdce6b30aeb4bb0cef00dfe3e.zip",
            "sha256": "2722d43a5e727afdcb82065732e0c71179c4114a179e2bd454b96025f0c1e382"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "doctrine_dbal-3.5.1.0",
            "urls": [
                "https://api.github.com/repos/doctrine/dbal/zipball/f38ee8aaca2d58ee88653cb34a6a3880c23f38a5"
            ],
            "cacheFile": "doctrine/dbal/e8e2f8ab8b3a4afa1524d57452c9871578b173b3.zip",
            "sha256": "ee69a6f62581eb3c3591eec3aae62c75baf77dcc81b9c5451cf98d64cc4b7b26"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "doctrine_deprecations-1.0.0.0",
            "urls": [
                "https://api.github.com/repos/doctrine/deprecations/zipball/0e2a4f1f8cdfc7a92ec3b01c9334898c806b30de"
            ],
            "cacheFile": "doctrine/deprecations/0b11d410b30a1fca6ad657a01bbf1bf8cb37b15b.zip",
            "sha256": "0948892861e2470c164fb0c45063967417c4b9e527ea4cf2b987030b047061ea"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "doctrine_doctrine-bundle-2.7.0.0",
            "urls": [
                "https://api.github.com/repos/doctrine/DoctrineBundle/zipball/d2088fc50494e4e7441fecca54732245a613eeb6"
            ],
            "cacheFile": "doctrine/doctrine-bundle/c41a5398165abf906af271c87431c2610fd12637.zip",
            "sha256": "c2309cc21eb8cc10e5a62d8ad96b811921132e5903381f0d1947a325bd9191bd"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "doctrine_doctrine-migrations-bundle-3.2.2.0",
            "urls": [
                "https://api.github.com/repos/doctrine/DoctrineMigrationsBundle/zipball/3393f411ba25ade21969c33f2053220044854d01"
            ],
            "cacheFile": "doctrine/doctrine-migrations-bundle/1f9868c4757b79572459b7a20aff9024345bf454.zip",
            "sha256": "f90d83ed4827a336156bb73a7624fda2ff94d46f2e24d40f1a145c8bec1d9880"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "doctrine_event-manager-1.2.0.0",
            "urls": [
                "https://api.github.com/repos/doctrine/event-manager/zipball/95aa4cb529f1e96576f3fda9f5705ada4056a520"
            ],
            "cacheFile": "doctrine/event-manager/b0da4be648d4609c3261c2d9f8b7bb9b691f3404.zip",
            "sha256": "72670f9ce249f3c5f657abf526a4c140a506822e19341f5eb379d72a91d02276"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "doctrine_inflector-2.0.6.0",
            "urls": [
                "https://api.github.com/repos/doctrine/inflector/zipball/d9d313a36c872fd6ee06d9a6cbcf713eaa40f024"
            ],
            "cacheFile": "doctrine/inflector/57c027282263baa14000cf3525eb68a5f0795e45.zip",
            "sha256": "12dae3b88886e0adde83b1d7338d2df7480620a0ec5ec8cde15935857b05defc"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "doctrine_instantiator-1.4.1.0",
            "urls": [
                "https://api.github.com/repos/doctrine/instantiator/zipball/10dcfce151b967d20fde1b34ae6640712c3891bc"
            ],
            "cacheFile": "doctrine/instantiator/b6977602bc07407dd2e3c71223021731d80df6d6.zip",
            "sha256": "e74aae2efad779dc6044b0b5d3ac4cf56eb41a511549ed35e6046cb4d6e0d7d4"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "doctrine_lexer-1.2.3.0",
            "urls": [
                "https://api.github.com/repos/doctrine/lexer/zipball/c268e882d4dbdd85e36e4ad69e02dc284f89d229"
            ],
            "cacheFile": "doctrine/lexer/4ab8440502eac4ce094502573b529bcbae3991e3.zip",
            "sha256": "1a329ce6ee5b48d38f7455631d0f9abd122643b304a112a6a76a50496d32e089"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "doctrine_migrations-3.5.2.0",
            "urls": [
                "https://api.github.com/repos/doctrine/migrations/zipball/61c6ef3a10b7df43c3b6388a184754f26e58700a"
            ],
            "cacheFile": "doctrine/migrations/6055b6ba32ffdba82b68a886749d13fe7e92b3be.zip",
            "sha256": "b72736dd283510518d667783bdf29d121ab483865c2f3097dbb7364d5322c531"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "doctrine_orm-2.13.3.0",
            "urls": [
                "https://api.github.com/repos/doctrine/orm/zipball/e750360bd52b080c4cbaaee1b48b80f7dc873b36"
            ],
            "cacheFile": "doctrine/orm/ea2b85da035e027aba6f0d0dddbe2494a5d8f5c1.zip",
            "sha256": "c0eb68cde818b28e23d336cd2697b72124259beb763ad0eb14e6e35ccc774e44"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "doctrine_persistence-3.0.4.0",
            "urls": [
                "https://api.github.com/repos/doctrine/persistence/zipball/05612da375f8a3931161f435f91d6704926e6ec5"
            ],
            "cacheFile": "doctrine/persistence/1b59ab4c84c72b4f315663c6144d5003cc0979a0.zip",
            "sha256": "3cbd9399fe6a5e76106589901a32bff536b843bd2e9f6eded38240ba6b5cc2c8"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "doctrine_sql-formatter-1.1.3.0",
            "urls": [
                "https://api.github.com/repos/doctrine/sql-formatter/zipball/25a06c7bf4c6b8218f47928654252863ffc890a5"
            ],
            "cacheFile": "doctrine/sql-formatter/27cb22cc3ac9fadaf29e9fdfc567a5373f122417.zip",
            "sha256": "835e8606783efcf94feb9bee7987bf67a47d27d0ba709bd4425a06a56bd61b6e"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "drupol_composer-plugin-nixify-2.0.7.0",
            "urls": [
                "https://api.github.com/repos/drupol/composer-plugin-nixify/zipball/56ece5e20dfa9402dd4058be35b893a08ed8aff1"
            ],
            "cacheFile": "drupol/composer-plugin-nixify/1e9ddfb441ea884c3aa529d65a4967447fd35c84.zip",
            "sha256": "8aff72b29081cd057dd4c87ca874ea0f67f8ae82cd879ee4824b311c9993d459"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "egulias_email-validator-3.2.1.0",
            "urls": [
                "https://api.github.com/repos/egulias/EmailValidator/zipball/f88dcf4b14af14a98ad96b14b2b317969eab6715"
            ],
            "cacheFile": "egulias/email-validator/6057c080143c0fb488917f6bcf0c04e4322f12a5.zip",
            "sha256": "b19dfc81a404989412dd7aa64fdcedbe3f8d57f325327e88e95ab9881a2004f0"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "friendsofphp_proxy-manager-lts-1.0.13.0",
            "urls": [
                "https://api.github.com/repos/FriendsOfPHP/proxy-manager-lts/zipball/88354616f4cf4f6620910fd035e282173ba453e8"
            ],
            "cacheFile": "friendsofphp/proxy-manager-lts/3741de9b1fbac34869f82570083768f2d96eadb2.zip",
            "sha256": "378a4cd426c3238f6ad90151b2bab09cd344b51b58ee77e514fecc0e1926d950"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "laminas_laminas-code-4.7.0.0",
            "urls": [
                "https://api.github.com/repos/laminas/laminas-code/zipball/0337d9265bc2e6376babad8c511500821620cb30"
            ],
            "cacheFile": "laminas/laminas-code/2e98f773684f1ab413a53a1872a9c094184baf40.zip",
            "sha256": "5cbcb4bfe7926c56875853cd21fa0bc19a9d003f54bb43bd0c37b7d16f1e488f"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "league_commonmark-2.3.5.0",
            "urls": [
                "https://api.github.com/repos/thephpleague/commonmark/zipball/84d74485fdb7074f4f9dd6f02ab957b1de513257"
            ],
            "cacheFile": "league/commonmark/7b71e79ed3aa44826b19a6ec33a87beb39f30ef5.zip",
            "sha256": "86cbe815d1ce36698e5ff7939ec755ae850619dd92170aed08a2d3bbc4b09a73"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "league_config-1.1.1.0",
            "urls": [
                "https://api.github.com/repos/thephpleague/config/zipball/a9d39eeeb6cc49d10a6e6c36f22c4c1f4a767f3e"
            ],
            "cacheFile": "league/config/93e5dff684dc813bc4800270d80a168895d5ffae.zip",
            "sha256": "76097ed5c4941c9ea3cf868544b6ad922b7252a21389e133ebeb5dd5ae719857"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "league_uri-6.8.0.0",
            "urls": [
                "https://api.github.com/repos/thephpleague/uri/zipball/a700b4656e4c54371b799ac61e300ab25a2d1d39"
            ],
            "cacheFile": "league/uri/d78e0e6337937a14dc8ddf00677ad4fccc5b2629.zip",
            "sha256": "5eabb50df8a715ed68f9fa86a996e25569f88e2e8599eb33cd32f8abaa1150ea"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "league_uri-interfaces-2.3.0.0",
            "urls": [
                "https://api.github.com/repos/thephpleague/uri-interfaces/zipball/00e7e2943f76d8cb50c7dfdc2f6dee356e15e383"
            ],
            "cacheFile": "league/uri-interfaces/abbfdfd0d9b6d6497ac2b5bcb6327c7ddd61493d.zip",
            "sha256": "dd6ca9a52521d7841729e3df05f16c679e8b77244c6ae398f444bb648da35406"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "masterminds_html5-2.7.6.0",
            "urls": [
                "https://api.github.com/repos/Masterminds/html5-php/zipball/897eb517a343a2281f11bc5556d6548db7d93947"
            ],
            "cacheFile": "masterminds/html5/08fb32e7137a83b9af783ead1339857fe23ac90e.zip",
            "sha256": "13303fbc8ce9e49c8229911922b83d06109deb1873b36b29050ec09af563d589"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "monolog_monolog-3.2.0.0",
            "urls": [
                "https://api.github.com/repos/Seldaek/monolog/zipball/305444bc6fb6c89e490f4b34fa6e979584d7fa81"
            ],
            "cacheFile": "monolog/monolog/50bd3361742360c2231ac757414509e58b4f9f4a.zip",
            "sha256": "2aef1a51ee450fbc1285d5c3cdc2687ff22377977eca04ae39b268820d51a8af"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "nette_schema-1.2.2.0",
            "urls": [
                "https://api.github.com/repos/nette/schema/zipball/9a39cef03a5b34c7de64f551538cbba05c2be5df"
            ],
            "cacheFile": "nette/schema/fa0f10d328ef5cb4ac44d52f794283a584d04a3b.zip",
            "sha256": "e242de33ed001f462beb2182a0f814195c96300b8b98c90ae286866ca2a225cf"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "nette_utils-3.2.8.0",
            "urls": [
                "https://api.github.com/repos/nette/utils/zipball/02a54c4c872b99e4ec05c4aec54b5a06eb0f6368"
            ],
            "cacheFile": "nette/utils/7a97696cf7eae03cf36f19358e039250a7a55e7f.zip",
            "sha256": "b7f0e56a6b31eda32ef5ef4cfae81739653919f5ef23ad038d0053d50730729e"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "psr_cache-3.0.0.0",
            "urls": [
                "https://api.github.com/repos/php-fig/cache/zipball/aa5030cfa5405eccfdcb1083ce040c2cb8d253bf"
            ],
            "cacheFile": "psr/cache/b7eac5d329f3f43db02b28fa0fef1a15080f3536.zip",
            "sha256": "88d63083b654a7ca847e926fcf8e3c35b0a7dd1bde960d8674ba10b2b8f4361f"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "psr_container-2.0.2.0",
            "urls": [
                "https://api.github.com/repos/php-fig/container/zipball/c71ecc56dfe541dbd90c5360474fbc405f8d5963"
            ],
            "cacheFile": "psr/container/a0a43e15cb16e3ab95a991e1bffc813474b15cdf.zip",
            "sha256": "3111f5b69d3a0f690f5f92d7aeacfb247f5ebd3c175088cce4b098e5d1b06ad7"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "psr_event-dispatcher-1.0.0.0",
            "urls": [
                "https://api.github.com/repos/php-fig/event-dispatcher/zipball/dbefd12671e8a14ec7f180cab83036ed26714bb0"
            ],
            "cacheFile": "psr/event-dispatcher/8f60a8cd1b7ff4e8f9782d70d78dee877a526529.zip",
            "sha256": "4d6a674cfd89a9957ead82e31ee4df785b2b1d215693add73184729a9a66d116"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "psr_http-message-1.0.1.0",
            "urls": [
                "https://api.github.com/repos/php-fig/http-message/zipball/f6561bf28d520154e4b0ec72be95418abe6d9363"
            ],
            "cacheFile": "psr/http-message/cc1d4e9ee13f2053b80c08976256789bf3be5256.zip",
            "sha256": "8538467ca2665fe15574f4d2506871823f71fd24b9a9284aae2ba90d8f69ada4"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "psr_log-3.0.0.0",
            "urls": [
                "https://api.github.com/repos/php-fig/log/zipball/fe5ea303b0887d5caefd3d431c3e61ad47037001"
            ],
            "cacheFile": "psr/log/4109d4b3f74b78a13cb175029bcb2384f59f0a52.zip",
            "sha256": "bbc23516c85615f2f85b707bc10ba26e62033e2afd696e075575b68dc6e31928"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "sensio_framework-extra-bundle-6.2.8.0",
            "urls": [
                "https://api.github.com/repos/sensiolabs/SensioFrameworkExtraBundle/zipball/bb962f8aed09e60b0942545f6e4842ffeee4aafd"
            ],
            "cacheFile": "sensio/framework-extra-bundle/4ad528a2d116fa0927c6c832b24e756462960f68.zip",
            "sha256": "9f99c326b2623b28f132af2191fab33e21155797d5893e5a6aa1ddfe454072dc"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_apache-pack-1.0.1.0",
            "urls": [
                "https://api.github.com/repos/symfony/apache-pack/zipball/3aa5818d73ad2551281fc58a75afd9ca82622e6c"
            ],
            "cacheFile": "symfony/apache-pack/fb283ab9da5768ac84cc04d17d491aca1004aaab.zip",
            "sha256": "66cfdb5c3e675e9d0f63c36511e7fdd9ac7b0f09be56ef19d64c0efb112c621e"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_asset-6.1.5.0",
            "urls": [
                "https://api.github.com/repos/symfony/asset/zipball/6065b5edc36442cb1ba98dc40f7c7f6b9e154729"
            ],
            "cacheFile": "symfony/asset/43c23d9f09198450a5e00f318297953666f17ac2.zip",
            "sha256": "70f890ea6f9367274dad939b0976b308c6f1fa3458987b5e0ccb29c8be354128"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_cache-6.1.5.0",
            "urls": [
                "https://api.github.com/repos/symfony/cache/zipball/9ae74e40fde37aba127ad5db65c5193f41f86f95"
            ],
            "cacheFile": "symfony/cache/2886d004053d24f9ad6355a564815d7e5150bd43.zip",
            "sha256": "fe365ad590c0146a85a0adad32c5fb928d9df296dccb088a5f4dbb6aa9b63d77"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_cache-contracts-3.1.1.0",
            "urls": [
                "https://api.github.com/repos/symfony/cache-contracts/zipball/2eab7fa459af6d75c6463e63e633b667a9b761d3"
            ],
            "cacheFile": "symfony/cache-contracts/08c94fdc95ee9f92c844cef8d4392410d490a34e.zip",
            "sha256": "efbc11fbc4455aacb5b0f7efcce44a04c1b5ccd2d2004ff249f66b07773bed9b"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_config-6.1.3.0",
            "urls": [
                "https://api.github.com/repos/symfony/config/zipball/a0645dc585d378b73c01115dd7ab9348f7d40c85"
            ],
            "cacheFile": "symfony/config/3b3ac4791d08b2ffc26b173ad83cae82ca8c0cbd.zip",
            "sha256": "53f68a17bc4ef2e76f9097b8b3731f177592178d9e335d6b9144ab4797d498c2"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_console-6.1.6.0",
            "urls": [
                "https://api.github.com/repos/symfony/console/zipball/7fa3b9cf17363468795e539231a5c91b02b608fc"
            ],
            "cacheFile": "symfony/console/d8112362a748c585b3d491a67d2c8551966ba170.zip",
            "sha256": "9d7aa9d5c210b8f7fb95b45d2eb8cb0a7968c187441cb2b1ebd5f5fa45e70df5"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_dependency-injection-6.1.5.0",
            "urls": [
                "https://api.github.com/repos/symfony/dependency-injection/zipball/b9c797c9d56afc290d4265854bafd01b4e379240"
            ],
            "cacheFile": "symfony/dependency-injection/d69ab2224d86d5beb750a9cca1fa79acb3816fbf.zip",
            "sha256": "65a53872a15a8db48017d515aeefbb3433fcb66b2480e170db6ed5bbb5cdb392"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_deprecation-contracts-3.1.1.0",
            "urls": [
                "https://api.github.com/repos/symfony/deprecation-contracts/zipball/07f1b9cc2ffee6aaafcf4b710fbc38ff736bd918"
            ],
            "cacheFile": "symfony/deprecation-contracts/dca2a27a37c80362e0b71ac9d045563c036fab83.zip",
            "sha256": "a0120eea2146c29e44bf2e62b0326e951b508483f202f4e3535ec5e546dcfea1"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_doctrine-bridge-6.1.6.0",
            "urls": [
                "https://api.github.com/repos/symfony/doctrine-bridge/zipball/5db7ac51c40d03d576b2696a6b55975e53a3dfd5"
            ],
            "cacheFile": "symfony/doctrine-bridge/954fc456cc9adef2f8f5792b7e70b338748bb9d9.zip",
            "sha256": "6ae4943e16ce817744d5c6151cb78cd466bf01770d9d8d57b9471221114dd9e4"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_dotenv-6.1.0.0",
            "urls": [
                "https://api.github.com/repos/symfony/dotenv/zipball/568c11bcedf419e7e61f663912c3547b54de51df"
            ],
            "cacheFile": "symfony/dotenv/3b87a27a8fe3b7b3cad536245ed5746c4674f088.zip",
            "sha256": "90ec48d5b6a9768e8431ba1ea242ba1f1f03aa61ed77343a820d6db6238ca25e"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_error-handler-6.1.6.0",
            "urls": [
                "https://api.github.com/repos/symfony/error-handler/zipball/49f718e41f1b6f0fd5730895ca5b1c37defd828d"
            ],
            "cacheFile": "symfony/error-handler/a43617694f10263b860b635f3724f65ae88742e4.zip",
            "sha256": "aaa4b9e2e28ac7151e6e75590ff0c85e86e2bfd8d29a86b8c6b49eed8066439c"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_event-dispatcher-6.1.0.0",
            "urls": [
                "https://api.github.com/repos/symfony/event-dispatcher/zipball/a0449a7ad7daa0f7c0acd508259f80544ab5a347"
            ],
            "cacheFile": "symfony/event-dispatcher/6519e03f5e3f5fb9f984630241cd390e7ae17642.zip",
            "sha256": "5d0db8bfdfe8f20d29bc973b82e783061e8a27c4e9edb3e3d9b5e429f1e022af"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_event-dispatcher-contracts-3.1.1.0",
            "urls": [
                "https://api.github.com/repos/symfony/event-dispatcher-contracts/zipball/02ff5eea2f453731cfbc6bc215e456b781480448"
            ],
            "cacheFile": "symfony/event-dispatcher-contracts/f28114759508333375723fb8106d3f9617376fc8.zip",
            "sha256": "10ee724c0f15db57db12b2b4f2878a26c8d5472dbe09e3c15534944e377d571e"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_expression-language-6.1.6.0",
            "urls": [
                "https://api.github.com/repos/symfony/expression-language/zipball/d1538560c075007d3dfd1f8e3a05e43a5ff13fd6"
            ],
            "cacheFile": "symfony/expression-language/f23e93ce4da7e6ebb62ba673684c7e39b279a6af.zip",
            "sha256": "498e5d567fd9799bf8e862c62f315eee6f6e62a89670508a72573f4ad4dbc401"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_filesystem-6.1.5.0",
            "urls": [
                "https://api.github.com/repos/symfony/filesystem/zipball/4d216a2beef096edf040a070117c39ca2abce307"
            ],
            "cacheFile": "symfony/filesystem/e92d85d1be4af65e2bab563beff7da7be8cc4c25.zip",
            "sha256": "d5c09bf21ff062af71f54b1d63305773a5bc35e92767ecd406f3d7fb261e28ad"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_finder-6.1.3.0",
            "urls": [
                "https://api.github.com/repos/symfony/finder/zipball/39696bff2c2970b3779a5cac7bf9f0b88fc2b709"
            ],
            "cacheFile": "symfony/finder/fa129088231144637abf06774bbdfe4881511cd6.zip",
            "sha256": "7d6be96be91ee89469629b249ba526767383affceaf0be3942f4fa83b5bc5ce4"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_flex-2.2.3.0",
            "urls": [
                "https://api.github.com/repos/symfony/flex/zipball/0763da1bdcce1d48c06778d48249905c26d34a72"
            ],
            "cacheFile": "symfony/flex/16267e558551355f4acd21567c407f682dda181b.zip",
            "sha256": "8c5534bf6afee08867058a8b69e5743880f8248eaf53c0c130b88f1b35e0da34"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_form-6.1.5.0",
            "urls": [
                "https://api.github.com/repos/symfony/form/zipball/176a358d54c70ec70708c7cbb4e8ac93cc138e6c"
            ],
            "cacheFile": "symfony/form/28f7dd75b23b852b33c43b1bafcad9c264913ae9.zip",
            "sha256": "cabbac2110ccc7a09db635fbb4720e233e982547e9dd646f9dbe299a5fe60214"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_framework-bundle-6.1.6.0",
            "urls": [
                "https://api.github.com/repos/symfony/framework-bundle/zipball/b79e5866a8293de00c8436836c2038ec31916ee7"
            ],
            "cacheFile": "symfony/framework-bundle/9f6b8c53561099d0cccd5c214e4ff3f81a049eb2.zip",
            "sha256": "daa720c866562f7fe88e76a012487e552cbbe28d529bda2f070758eed83c2ec2"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_html-sanitizer-6.1.0.0",
            "urls": [
                "https://api.github.com/repos/symfony/html-sanitizer/zipball/28d19124099e860ef52da06ae251e37738b750fe"
            ],
            "cacheFile": "symfony/html-sanitizer/50543e0f71f906d156aaa3d6db60db41b413cda2.zip",
            "sha256": "448988f315de7c72b60a345ed53b7c2c6303983a77ccfbc105ac2bde2e6a50b5"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_http-client-6.1.6.0",
            "urls": [
                "https://api.github.com/repos/symfony/http-client/zipball/c8c887f4813370550147afd27d9eb8a8523e53b2"
            ],
            "cacheFile": "symfony/http-client/04c179e5c8472f8c3fc9669c4c3ff74bd366cedf.zip",
            "sha256": "b2fc3f27070e9167003b4a6f7ddf458efd9448c0e34b492ce4e9d6f34acf3f06"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_http-client-contracts-3.1.1.0",
            "urls": [
                "https://api.github.com/repos/symfony/http-client-contracts/zipball/fd038f08c623ab5d22b26e9ba35afe8c79071800"
            ],
            "cacheFile": "symfony/http-client-contracts/b853e2699b173be227957bc9516c051e2d40fdbb.zip",
            "sha256": "1b8a5b9f4fb2d2261148e280f6a65fdbe101210a91786327dfcc2256b18d4f9a"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_http-foundation-6.1.6.0",
            "urls": [
                "https://api.github.com/repos/symfony/http-foundation/zipball/3ae8e9c57155fc48930493a629da293b32efbde0"
            ],
            "cacheFile": "symfony/http-foundation/0fbeddbfc917fd1377261e4aeae61df148d96475.zip",
            "sha256": "ff6a07737a0e5121dfbf7e599e3fc4b9d7413f289210f690ae677dea4c325d0f"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_http-kernel-6.1.6.0",
            "urls": [
                "https://api.github.com/repos/symfony/http-kernel/zipball/102f99bf81799e93f61b9a73b2f38b309c587a94"
            ],
            "cacheFile": "symfony/http-kernel/bac9427a29c8634ee3559e105eca9f6616d8c6a4.zip",
            "sha256": "1e98a316eae91e897f4650e4525deaf68cda31081589e0e9cb0091b581f8fde7"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_intl-6.1.6.0",
            "urls": [
                "https://api.github.com/repos/symfony/intl/zipball/9ab546d9054b34feb2cb728349f6b8e8f18d4c43"
            ],
            "cacheFile": "symfony/intl/2006547f77ebb5ef0ed5dafa75e933ff5569d6f6.zip",
            "sha256": "f51a25fadf19c5234805e785143681919920bae0649fce9e737821733535498e"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_mailer-6.1.5.0",
            "urls": [
                "https://api.github.com/repos/symfony/mailer/zipball/e1b32deb9efc48def0c76b876860ad36f2123e89"
            ],
            "cacheFile": "symfony/mailer/3cdb3f354ae19a0dfc072aeb4a4bbee3b9a3ccfb.zip",
            "sha256": "7391ac9a75e66dc397893b5edc20147375892a6544bcc9ae258942a68b9c4f5c"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_mime-6.1.6.0",
            "urls": [
                "https://api.github.com/repos/symfony/mime/zipball/5ae192b9a39730435cfec025a499f79d05ac68a3"
            ],
            "cacheFile": "symfony/mime/34a37d5b9b9235cf258a4e916b661897ccad226a.zip",
            "sha256": "56edb213f8c657c7ac38135e5bd571e030ef096dc6c3ceff4633ccc5b06a4719"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_monolog-bridge-6.1.2.0",
            "urls": [
                "https://api.github.com/repos/symfony/monolog-bridge/zipball/1efd6a42b1dc80e03bd74d4a2fdc85e728dc2627"
            ],
            "cacheFile": "symfony/monolog-bridge/36ca055cf021cc97e43dca1695d8e1303f3e2c6e.zip",
            "sha256": "fa7924eb7c8fe1cec9f1460268841693614e06749a725f8d00471794a4ed6089"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_monolog-bundle-3.8.0.0",
            "urls": [
                "https://api.github.com/repos/symfony/monolog-bundle/zipball/a41bbcdc1105603b6d73a7d9a43a3788f8e0fb7d"
            ],
            "cacheFile": "symfony/monolog-bundle/4f7c43127ae12a5d0bebc28db86c81606a5f8c0d.zip",
            "sha256": "6a2253726b5b4d06558d96b67a5e01babd1f86e1d47fb28c907256dc335b008f"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_options-resolver-6.1.0.0",
            "urls": [
                "https://api.github.com/repos/symfony/options-resolver/zipball/a3016f5442e28386ded73c43a32a5b68586dd1c4"
            ],
            "cacheFile": "symfony/options-resolver/60e4cbdd9e32259303e19828de6c0d0c131d3266.zip",
            "sha256": "07684f41129acf52ca029993d4b7feac1f1dc5f5e7db7e956e65d968b75cbdc0"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_password-hasher-6.1.3.0",
            "urls": [
                "https://api.github.com/repos/symfony/password-hasher/zipball/264894821636b77bb8282db6ec33b8b07b7a0678"
            ],
            "cacheFile": "symfony/password-hasher/b6b394adb4593054def762919abb199c8857be25.zip",
            "sha256": "28a34a0fe270c80c329c4f1b55ab167ba8d593cb778729d93279f8dc2b39c1e2"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_polyfill-ctype-1.26.0.0",
            "urls": [
                "https://api.github.com/repos/symfony/polyfill-ctype/zipball/6fd1b9a79f6e3cf65f9e679b23af304cd9e010d4"
            ],
            "cacheFile": "symfony/polyfill-ctype/81dd04d88f1f9151715ddca6520173db239a8db9.zip",
            "sha256": "6ae1955d8f7b5d18967a3f5bcb910cd664fc7da9d4ff3bfab7a9cb8b632f43a0"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_polyfill-intl-grapheme-1.26.0.0",
            "urls": [
                "https://api.github.com/repos/symfony/polyfill-intl-grapheme/zipball/433d05519ce6990bf3530fba6957499d327395c2"
            ],
            "cacheFile": "symfony/polyfill-intl-grapheme/d3a40f7624005537657f7b2390e399d9892be5cd.zip",
            "sha256": "8f85460e03a1ec08d2c3d4faf9beb397e00d91ca2a06b3422a19d634a04c2684"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_polyfill-intl-icu-1.26.0.0",
            "urls": [
                "https://api.github.com/repos/symfony/polyfill-intl-icu/zipball/e407643d610e5f2c8a4b14189150f68934bf5e48"
            ],
            "cacheFile": "symfony/polyfill-intl-icu/4101dc07f0bf63d572ef1173ef9b798fe1dd03a8.zip",
            "sha256": "07d6f5daccc0e79e226adb5b8f8f1c18de8a8f545aa371e7fd5857b1aecc6d36"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_polyfill-intl-idn-1.26.0.0",
            "urls": [
                "https://api.github.com/repos/symfony/polyfill-intl-idn/zipball/59a8d271f00dd0e4c2e518104cc7963f655a1aa8"
            ],
            "cacheFile": "symfony/polyfill-intl-idn/f528fbe65e0b1fba3575d8ecf47747161ac8134d.zip",
            "sha256": "bb5804f465ea89a4a8008cc5b7505f5cf5de3a366609be39d7b5812811a18dad"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_polyfill-intl-messageformatter-1.26.0.0",
            "urls": [
                "https://api.github.com/repos/symfony/polyfill-intl-messageformatter/zipball/5c17bd6ee46b77d6bbb002c5a51ac1d5b5bb1452"
            ],
            "cacheFile": "symfony/polyfill-intl-messageformatter/0d2b3a1ccd490aae0d5e68384a110b86253d406d.zip",
            "sha256": "381fa1741f7b906eef095e0f23f3e80a352d0115361ab6e12c7e2182354a5aeb"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_polyfill-intl-normalizer-1.26.0.0",
            "urls": [
                "https://api.github.com/repos/symfony/polyfill-intl-normalizer/zipball/219aa369ceff116e673852dce47c3a41794c14bd"
            ],
            "cacheFile": "symfony/polyfill-intl-normalizer/4eef99810616b77605bb089d8dfd1f79ebf9b434.zip",
            "sha256": "5c0817d99bfb7c0399f67c5e447a06d73a8c38961c41a97d8ae412fc559e8cb3"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_polyfill-mbstring-1.26.0.0",
            "urls": [
                "https://api.github.com/repos/symfony/polyfill-mbstring/zipball/9344f9cb97f3b19424af1a21a3b0e75b0a7d8d7e"
            ],
            "cacheFile": "symfony/polyfill-mbstring/54165ccd6617b49a7c13c7ce6515c2f36a6ecec4.zip",
            "sha256": "081b68a5b03baf94d4b0fe096b497c9a26e7155d45f64837ca8f2616524f4878"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_property-access-6.1.3.0",
            "urls": [
                "https://api.github.com/repos/symfony/property-access/zipball/25108ee9b62d6ef0815007d9c7cf6a7ba40bb7c5"
            ],
            "cacheFile": "symfony/property-access/237a114456ee75331a9cbcf57d607e3be5878882.zip",
            "sha256": "1cd1519f7fe0ddc6be36edafb2536033b5be2aa8988d6af4452a48c4989b54fb"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_property-info-6.1.6.0",
            "urls": [
                "https://api.github.com/repos/symfony/property-info/zipball/f28d0db9d2687f81d68d0dc6b2e42817647f5d64"
            ],
            "cacheFile": "symfony/property-info/e9b66d9a9db374de2de0ed4533e899c235c0611e.zip",
            "sha256": "5b00cdb83d08689e0185cd34cf15ffeef8ce323cd38adfae96ecded221572389"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_routing-6.1.5.0",
            "urls": [
                "https://api.github.com/repos/symfony/routing/zipball/f8c1ebb43d0f39e5ecd12a732ba1952a3dd8455c"
            ],
            "cacheFile": "symfony/routing/73482160307fdd6aa6ede414b453fe3aa89854f5.zip",
            "sha256": "b1feb2912177d2c1ad965100765b89ad095a94444286761d198bcf1bef59dd6b"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_runtime-6.1.3.0",
            "urls": [
                "https://api.github.com/repos/symfony/runtime/zipball/e5d4d848656cbb1812d5f911b1bdec205c6e2fac"
            ],
            "cacheFile": "symfony/runtime/56b305379dfae48dafe836bfb9aae6102eac29c8.zip",
            "sha256": "e7b86324cf10fc8534d95e7d8938f1ddaf8f3b93529b6267d23ff8afe41b3957"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_security-bundle-6.1.3.0",
            "urls": [
                "https://api.github.com/repos/symfony/security-bundle/zipball/1410129e36e5d0cf4bde73f4ed5d9e18acff06b3"
            ],
            "cacheFile": "symfony/security-bundle/a0977dad4271f7f36a6873c2d40301acb16ccd7d.zip",
            "sha256": "5e1e19234d1a1e0b23df129db55cb71a994d8ca340691b90a07da084b6d25b8b"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_security-core-6.1.6.0",
            "urls": [
                "https://api.github.com/repos/symfony/security-core/zipball/e42fb611d1a36e6e1e34f8cd715cea108a39cad5"
            ],
            "cacheFile": "symfony/security-core/6312a8ffd9a237b148bfcba96afb596d532ebb39.zip",
            "sha256": "f065815b743a0e9c193033214de5527c253e811ee634359eeeaa6260c3d626f1"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_security-csrf-6.1.0.0",
            "urls": [
                "https://api.github.com/repos/symfony/security-csrf/zipball/b44d74295a5651298de8c2760ba50bef3b97f34b"
            ],
            "cacheFile": "symfony/security-csrf/60b6dba6abeea958e091ae6d99acb39101a01c85.zip",
            "sha256": "ebede5764061b3b29af0b35f3143d65cd131f7bc80dd44b0855f7b2ceb58cc15"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_security-http-6.1.6.0",
            "urls": [
                "https://api.github.com/repos/symfony/security-http/zipball/789492510f7127035da8bb5dbb4fb745970e2348"
            ],
            "cacheFile": "symfony/security-http/e0d4d0d77925ad777ad9e4409a2814d76021ac3f.zip",
            "sha256": "e3464dbda12ec19f34efa83b2d078c23ffd8c0d286031da11b5cce679aea8d91"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_service-contracts-3.1.1.0",
            "urls": [
                "https://api.github.com/repos/symfony/service-contracts/zipball/925e713fe8fcacf6bc05e936edd8dd5441a21239"
            ],
            "cacheFile": "symfony/service-contracts/81a30ff05900d7fc2466c0df3cf18fe0839f9d1d.zip",
            "sha256": "5e684049f405368d934ec578e7079f31937415a78eac5638c590b707027624af"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_stopwatch-6.1.5.0",
            "urls": [
                "https://api.github.com/repos/symfony/stopwatch/zipball/266636bb8f3fbdccc302491df7b3a1b9a8c238a7"
            ],
            "cacheFile": "symfony/stopwatch/cbd47bd4a836573d7038ef94db98b53d79d717a4.zip",
            "sha256": "9b7fc660c8e6e5e8062a912b42af0973ca30b2f26b28a38e4cac915feb8022a6"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_string-6.1.6.0",
            "urls": [
                "https://api.github.com/repos/symfony/string/zipball/7e7e0ff180d4c5a6636eaad57b65092014b61864"
            ],
            "cacheFile": "symfony/string/fa91874785e6f2814b28a207357d1ed170f7094f.zip",
            "sha256": "99622da364f0f19e354fc62cc06a9b9fb6d57c1edcd6585892f4a04f33070c61"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_translation-6.1.6.0",
            "urls": [
                "https://api.github.com/repos/symfony/translation/zipball/e6cd330e5a072518f88d65148f3f165541807494"
            ],
            "cacheFile": "symfony/translation/83a22194e0d41d73379055055fc00e0492eb9934.zip",
            "sha256": "93239d9db8ee8c04cd3a6f16aee0426c6eb58615ea5a2b601a1d6dd4be38bf4d"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_translation-contracts-3.1.1.0",
            "urls": [
                "https://api.github.com/repos/symfony/translation-contracts/zipball/606be0f48e05116baef052f7f3abdb345c8e02cc"
            ],
            "cacheFile": "symfony/translation-contracts/9bbe39cdcfce22145c22f505fd88eb2a08495614.zip",
            "sha256": "4f781e2bd009efcb36cbd96c06857cfd8989e5fa63b2fd387aaf7b5dff011a3c"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_twig-bridge-6.1.6.0",
            "urls": [
                "https://api.github.com/repos/symfony/twig-bridge/zipball/368e9bac2dbaed85d943745b521077f8101b599d"
            ],
            "cacheFile": "symfony/twig-bridge/ef3d2f78c374c167713fd0a3de106f6177fed704.zip",
            "sha256": "1da58a0bab519535a0135604b362113f8b6b11fa32df684025314668a6cc4beb"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_twig-bundle-6.1.1.0",
            "urls": [
                "https://api.github.com/repos/symfony/twig-bundle/zipball/a2abab10068525a7f5a879e40e411d369d688545"
            ],
            "cacheFile": "symfony/twig-bundle/f11603035cced39691f170941067e8ad0e980b40.zip",
            "sha256": "b611356e9d663c28ef47eb4cb319e8dfda66907740593247829fe923bb34a52a"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_validator-6.1.6.0",
            "urls": [
                "https://api.github.com/repos/symfony/validator/zipball/e5589882403e1e19774d7c5ffb65d9c6466d216c"
            ],
            "cacheFile": "symfony/validator/2c8415d664b4c17dd0cdf4680784c68dcaf2433b.zip",
            "sha256": "0262801290e70fb6f9f1d394d5e96aa1cf64c99f9b0ebb0f9d4bb974a3e817b2"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_var-dumper-6.1.6.0",
            "urls": [
                "https://api.github.com/repos/symfony/var-dumper/zipball/0f0adde127f24548e23cbde83bcaeadc491c551f"
            ],
            "cacheFile": "symfony/var-dumper/2a7e178c6e9332064f40a8e6653b7faa59b6d315.zip",
            "sha256": "ef96837ffca5662daebb00953c886f96fab612d0299035b93a73e0068931c982"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_var-exporter-6.1.3.0",
            "urls": [
                "https://api.github.com/repos/symfony/var-exporter/zipball/b49350f45cebbba6e5286485264b912f2bcfc9ef"
            ],
            "cacheFile": "symfony/var-exporter/2bc3fa75d2ccd1e41136a3177102255a11d17118.zip",
            "sha256": "1ebd5a3924808ff29e52d28ed00d5e0f9fdb875bf5dd189d5792d6698d20846e"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_webpack-encore-bundle-1.16.0.0",
            "urls": [
                "https://api.github.com/repos/symfony/webpack-encore-bundle/zipball/bb399930c0299866258b616a74a27b50b94c5d45"
            ],
            "cacheFile": "symfony/webpack-encore-bundle/2aaca8e5b7b984dc561e6d7c174a6950ebd609da.zip",
            "sha256": "793066604ee15bbf22e252ecd4dd6b3cea611bde1eb5267a58a00b2112d73c54"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_yaml-6.1.6.0",
            "urls": [
                "https://api.github.com/repos/symfony/yaml/zipball/66c6b0cf52b00f74614a2cf7ae7db08ea1095931"
            ],
            "cacheFile": "symfony/yaml/6482b642b0fb35c98f88773a8d73b38246eeb371.zip",
            "sha256": "b2fe6da941f4df5abdcd0dd5fecf09fef58af22bee5b7c91a3ce540f12490f31"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "twig_extra-bundle-3.4.0.0",
            "urls": [
                "https://api.github.com/repos/twigphp/twig-extra-bundle/zipball/2e58256b0e9fe52f30149347c0547e4633304765"
            ],
            "cacheFile": "twig/extra-bundle/bbb8c8ce231d65114e94e0e7dd7d1a69285e689f.zip",
            "sha256": "f9808a10728c2f0bbf6b7a4903bd97d7f238b324f92ac75b95ce6bdff8b6f055"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "twig_intl-extra-3.4.2.0",
            "urls": [
                "https://api.github.com/repos/twigphp/intl-extra/zipball/151e50fad9c7915bd56f0adf3f0cb3c47e6ed28a"
            ],
            "cacheFile": "twig/intl-extra/3626f9a521c1328b4aa1534964c2143421e39336.zip",
            "sha256": "d45f3176af6a11b2b993958206754e28bb8e4b75a01b22aa75fdc0af87736e00"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "twig_markdown-extra-3.4.0.0",
            "urls": [
                "https://api.github.com/repos/twigphp/markdown-extra/zipball/25ed505b6ffd3b00f922ca682489dfbaf44eb1f7"
            ],
            "cacheFile": "twig/markdown-extra/b4cdef880599a26f520f4d0e014687d3c874f28a.zip",
            "sha256": "1c94477ae013a15b75569e611f68b6f0fadf5d82b60b1adc0f1d4ad2647f9a5d"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "twig_twig-3.4.3.0",
            "urls": [
                "https://api.github.com/repos/twigphp/Twig/zipball/c38fd6b0b7f370c198db91ffd02e23b517426b58"
            ],
            "cacheFile": "twig/twig/c327b80bbe117f041a0ec13b5be25e1afcc21bff.zip",
            "sha256": "e849b8f7a146fe77065713bb6a6d6d2ffbe8109f0c7df2ee2413b4b7fe464840"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "dama_doctrine-test-bundle-7.1.1.0",
            "urls": [
                "https://api.github.com/repos/dmaicher/doctrine-test-bundle/zipball/279a554556bed387a6aaae0c13cc982d4874773b"
            ],
            "cacheFile": "dama/doctrine-test-bundle/200257585b9a249b36e84ac42f69ace28fb6cbd7.zip",
            "sha256": "25ca5076be748c6589a45d31c43f38e8789d1773c7b192644e00f867ce3b7519"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "doctrine_data-fixtures-1.5.3.0",
            "urls": [
                "https://api.github.com/repos/doctrine/data-fixtures/zipball/ba37bfb776de763c5bf04a36d074cd5f5a083c42"
            ],
            "cacheFile": "doctrine/data-fixtures/aa469e849b9224f55b47401ebb9921fedbc39ee0.zip",
            "sha256": "77cfc290103d63784208feb93e16b9241851e6c42d81b76f7994ec4c3a4aef47"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "doctrine_doctrine-fixtures-bundle-3.4.2.0",
            "urls": [
                "https://api.github.com/repos/doctrine/DoctrineFixturesBundle/zipball/601988c5b46dbd20a0f886f967210aba378a6fd5"
            ],
            "cacheFile": "doctrine/doctrine-fixtures-bundle/c02fc4f1ca8abf546b600dd2c7e55afb9321e7c9.zip",
            "sha256": "b77d30128ce1bbc4c4cee2bc8f30fb40533bf4d4c603ac7ae5e7fa475a8759eb"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "nikic_php-parser-4.15.1.0",
            "urls": [
                "https://api.github.com/repos/nikic/PHP-Parser/zipball/0ef6c55a3f47f89d7a374e6f835197a0b5fcf900"
            ],
            "cacheFile": "nikic/php-parser/1eb86a27836221d0f0d8af8423dabc73c22322d1.zip",
            "sha256": "6bc19dc410fd00ef6ca1be0594bb979e2e8fd5b143ea7a399b8fde92e2b8ba02"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "phpstan_phpstan-1.8.11.0",
            "urls": [
                "https://api.github.com/repos/phpstan/phpstan/zipball/46e223dd68a620da18855c23046ddb00940b4014"
            ],
            "cacheFile": "phpstan/phpstan/f6dad7f31c17e1b2ef14de6042a9cdd7ed1e3267.zip",
            "sha256": "bbf9aedb5ba7a7d7a8762b87d8db803e838c1d145308cfb69def9f681628b585"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_browser-kit-6.1.3.0",
            "urls": [
                "https://api.github.com/repos/symfony/browser-kit/zipball/2e3b6a4406c2af963c634d7bd0457402b67dcc56"
            ],
            "cacheFile": "symfony/browser-kit/1eadb1d5e04d604a3716a5500178eef75a0cd1a9.zip",
            "sha256": "d64385916b6c03e2bfd28e92e0b48a1e1d11b746128772ff1104c503a7cf3dbd"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_css-selector-6.1.3.0",
            "urls": [
                "https://api.github.com/repos/symfony/css-selector/zipball/0dd5e36b80e1de97f8f74ed7023ac2b837a36443"
            ],
            "cacheFile": "symfony/css-selector/d053d544440770ce9bfca4e43857a5cf9bf44ade.zip",
            "sha256": "ab5fe8aa0c69d6fe8137a0f6527bbc616e5a80ec41029c9ee51a07c9db2e4254"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_debug-bundle-6.1.3.0",
            "urls": [
                "https://api.github.com/repos/symfony/debug-bundle/zipball/4084f86639bf0270d6dd2225fc8d7c317780dd6b"
            ],
            "cacheFile": "symfony/debug-bundle/9cefd810b7406525337c61373aec25bca6ffcd8c.zip",
            "sha256": "c7aee1065c926cb150c553961a5617e618c62d5ecf4ccfb8a1625baca124e2d3"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_dom-crawler-6.1.4.0",
            "urls": [
                "https://api.github.com/repos/symfony/dom-crawler/zipball/8cb4c6e6c8d30c26f70529ed5e50d79a09576c0c"
            ],
            "cacheFile": "symfony/dom-crawler/827d3b1306ee2ecc46e3307ad22c2eac9989a5c6.zip",
            "sha256": "728a1d88cfce67ec71d1278695101bc6f5ae3b86df691906fa8760f83a4d168f"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_maker-bundle-1.47.0.0",
            "urls": [
                "https://api.github.com/repos/symfony/maker-bundle/zipball/e607f129d29a6c1e9a9e1ef3d229d653311d58f3"
            ],
            "cacheFile": "symfony/maker-bundle/1a56e66f2d313911eac53c3599f8e10e0e501913.zip",
            "sha256": "e08e9957db6e5f795f22bb673b5a267dfb97948ab768133b5bec2f55b55e9868"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_phpunit-bridge-6.1.6.0",
            "urls": [
                "https://api.github.com/repos/symfony/phpunit-bridge/zipball/07cf788ac9ae83b59d46599bb5098c3add88c68b"
            ],
            "cacheFile": "symfony/phpunit-bridge/aa8f8d4d9b64848ff650ce8e46ce5d81aef20fb8.zip",
            "sha256": "47a1aba8816b38e653c31b99bac854299ee43e1d8cfafe7d107b1161f73f0bf1"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "symfony_web-profiler-bundle-6.1.6.0",
            "urls": [
                "https://api.github.com/repos/symfony/web-profiler-bundle/zipball/45d05cd8e967fd06bb1f66f748ed308c00674d32"
            ],
            "cacheFile": "symfony/web-profiler-bundle/05ee4f5ea3e05f767869175bfa0a04a527bfc7a5.zip",
            "sha256": "256ade9137c52e167c404c27a49302e1da865c50d27e09d6bb529c01e5100810"
        }
    ],
    "projectName": "symfony_symfony-demo"
}
  '';
  composerPath = data.composerPath or phpPackages.composer.src;
  cacheEntries = data.cacheEntries or [];
  localEntries = data.localEntries or [];

  # Shell snippet to collect all project dependencies.
  collectCacheScript = writeText "collect-cache.sh" (
    concatMapStrings (args: ''
      (
        cacheFile=${escapeShellArg args.cacheFile}
        cacheFilePath="$COMPOSER_CACHE_DIR/files/$cacheFile"
        mkdir -p "$(dirname "$cacheFilePath")"
        cp ${escapeShellArg (fetcher args)} "$cacheFilePath"
      )
    '') cacheEntries
  );

  replaceLocalPaths = writeText "replace-local-paths.sh" (
    concatMapStrings (args: ''
      sed -i -e "s|\"${args.string}\"|\"${args.path}\"|" composer.lock
    '') localEntries
  );

in stdenv.mkDerivation {
  name = data.projectName;
  inherit src;

  # Make sure the build uses the right PHP version everywhere.
  # Also include unzip for Composer.
  buildInputs = [ php unzip ];

  # Defines the shell alias to run Composer.
  postHook = ''
    composer () {
      php "$NIX_COMPOSER_PATH" "$@"
    }
  '';

  configurePhase = ''
    runHook preConfigure

    # Set the cache directory for Composer.
    export COMPOSER_CACHE_DIR="$NIX_BUILD_TOP/.composer/cache"

    # Build the cache directory contents.
    source ${collectCacheScript}

    # Replace local package paths with their Nix store equivalent.
    source ${replaceLocalPaths}

    # Store the absolute path to Composer for the 'composer' alias.
    export NIX_COMPOSER_PATH="$(readlink -f ${escapeShellArg composerPath})"

    # Run normal Composer install to complete dependency installation.
    composer install -n -o

    runHook postConfigure
  '';

  buildPhase = ''
    runHook preBuild
    runHook postBuild
  '';

  installPhase = ''
    runHook preInstall

    mkdir -p $out/libexec $out/bin

    # Move the entire project to the output directory.
    mv $PWD "$out/libexec/$sourceRoot"
    cd "$out/libexec/$sourceRoot"

    # Update the path to Composer.
    export NIX_COMPOSER_PATH="$(readlink -f ${escapeShellArg composerPath})"

    # Invoke a plugin internal command to setup binaries.
    # composer nixify-install-bin "$out/bin"

    runHook postInstall
  '';

  passthru = {
    inherit php;
  };
}
